### ISSUE TITLE
Dynamic view for each dimension.

### ISSUE THREAD

**Issue by Banaando** [ldtteam/DynView#37]
Would be great if this mod could adjust the simulation and view distance on a per dimension basis instead of adjusting it on the whole server.

**Comment by someaddons** [comment]
There is little reason to do so, as all dimensions run together in the same loop so lag affects them all equally

**Comment by Magicrafter13** [comment]
> There is little reason to do so, as all dimensions run together in the same loop so lag affects them all equally

My server gets far more lag from the nether because there are more mobs to tick, and, the nether is not a dimension that benefits from long render distance as much as the other two do.

There's definitely good reasons to prioritize one dimension over the other. I don't want lag to cause all dimensions to scale equally. I would prefer to give more resources towards the overworld which matters most.
